import type { Metadata } from 'next'

import { ReactQueryProvider } from '@/shared/lib/react-query/provider'
import { Navigation } from '@/shared/ui/navigation'
import { EffectorNext } from '@effector/next'
import {
  ColorSchemeScript,
  createTheme,
  DEFAULT_THEME,
  mantineHtmlProps,
  MantineProvider,
} from '@mantine/core'
import { Overpass, Overpass_Mono } from 'next/font/google'

import '@mantine/core/styles.css'
// import after @mantine/core/styles.css
import '@mantine/charts/styles.css'
import './globals.css'

const overpass = Overpass({
  variable: '--font-overpass',
  subsets: ['cyrillic'],
})

const overpassMono = Overpass_Mono({
  variable: '--font-overpass-mono',
  subsets: ['cyrillic'],
})

const theme = createTheme({
  fontFamily: `var(--font-overpass), ${DEFAULT_THEME.fontFamily}`,
  fontFamilyMonospace: `var(--font-overpass-mono), monospace`,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang='ru'
      className={`${overpass.variable} ${overpassMono.variable}`}
      {...mantineHtmlProps}
    >
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <Navigation>
            <EffectorNext>
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </EffectorNext>
          </Navigation>
        </MantineProvider>
      </body>
    </html>
  )
}
