import type { Metadata } from 'next'

import { ReactQueryProvider } from '@/shared/lib/react-query/provider'
import { Navigation } from '@/shared/ui/navigation'
import { EffectorNext } from '@effector/next'
import { Overpass, Overpass_Mono } from 'next/font/google'

import './globals.css'

const overpass = Overpass({
  variable: '--font-overpass',
  subsets: ['cyrillic'],
})

const overpassMono = Overpass_Mono({
  variable: '--font-overpass-mono',
  subsets: ['cyrillic'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ru'>
      <body className={`${overpass.variable} ${overpassMono.variable} font-sans antialiased`}>
        <header className='border-b border-border'>
          <Navigation />
        </header>
        <main>
          <EffectorNext>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </EffectorNext>
        </main>
      </body>
    </html>
  )
}
